### ISSUE TITLE
Type checking is a breaking change

### ISSUE THREAD

**Issue by arthot** [skolmer/es2015-i18n-tag#53] opened 2018-07-19 16:07 UTC
Hi!

The latest release (1.4.0) introduced a new functionality "**added type checks to localizers**". And it's definitely a breaking change, because it breaks code like
```javascript
const total = 6;
i18n`Up to ${total} integrations`
```

So at least it should be a major version change. But in my opinion the project shouldn't have this functionality at all, because what is wrong with this code?  It's pretty straightforward, you can always use `.toString()` implicitly, and after all it's a JavaScript, a language where you don't care about types  and can spit on OOP :smile:

**Comment by skolmer** [comment] 2018-07-21 14:32
sorry, this was not intended. It should only check if you use type formatters for date and number formats. 
It was intended to give a better debugging experience if you accidentally format a null/undefined or some other object as date or number like ``` i18n`Current Date: ${null}:t(D)` ```

**Comment by skolmer** [comment] 2018-10-06 22:40
sorry for the huge delay, I have so much work on my desk right now. happy to receive a pull request on this topic but also willing to work on this as soon as I find some free time.

**Comment by skolmer** [comment] 2018-11-16 11:48
Fixed in 1.4.1

**Closed by skolmer** 2018-11-16 11:48 UTC
Labels: bug
